### ISSUE TITLE
performances

### ISSUE THREAD

**Issue by thegodone** [sagawatatsuya/ReactionT5v2#4]
In Huggingface model you put this https://huggingface.co/sagawa/ReactionT5v2-forward : 
![image](https://github.com/user-attachments/assets/dee62696-e062-4735-b2f1-91dbc7b49818)
What is the corresponding line ReactionT5 (This model) or the next (last) line ReactionT5 ? Same for the  two others models. Do I need to retrained / fine-tune or not ?

**Comment by sagawatatsuya** [comment]
We currently provide only the model weight pretrained on the ORD dataset. By applying this model to the USPTO_MIT test split, you can achieve the same performance of "ReactionT5 (This model)" on that table. To achieve the performance of the last line of that table, you have to train this model further on USPTO_MIT's train split.

**Comment by thegodone** [comment]
Wonderful, thanks for explainartions. for retrosynthesis, I guess I should also do the same but with USPTO_50k ?

**Comment by sagawatatsuya** [comment]
Yes, that is correct.

**Comment by thegodone** [comment]
Can you provide exact code to train both models please, or even better give access to the final best two models ? 
I am benchmarking 9 models and we got the best model in principal.

**Comment by sagawatatsuya** [comment]
I uploaded the forward reaction prediction model fine-tuned with USPTO_MIT: [link](https://huggingface.co/sagawa/ReactionT5v2-forward-USPTO_MIT)
and the retrosynthesis prediction model fine-tuned with USPTO_50k: [link](https://huggingface.co/sagawa/ReactionT5v2-retrosynthesis-USPTO_50k)

**Comment by thegodone** [comment]
thanks a lot

**Comment by thegodone** [comment]
I just need to change default="sagawa/ReactionT5v2-retrosynthesis-USPTO_50k" or  default="sagawa/ReactionT5v2-forward-USPTO_MIT" in respective prediction.py files. 
One remark, default value for retrosynthesis is not pointing to default v2 version but default="sagawa/ReactionT5-product-prediction". https://github.com/sagawatatsuya/ReactionT5v2/blob/8921fc96f631d291e8a602fe8ca7646b8f11845f/task_retrosynthesis/prediction.py#L54C1-L55C1

**Comment by sagawatatsuya** [comment]
You can use other models for prediction by specifying "--model_name_or_path" when executing the inference command.
If you want to use "sagawa/ReactionT5v2-retrosynthesis-USPTO_50k" instead of "sagawa/ReactionT5v2-retrosynthesis", use this command:
```
cd task_retrosynthesis
python prediction.py \
    --input_data="../data/task_retrosynthesis_demo_input.csv" \
    --model_name_or_path="sagawa/ReactionT5v2-retrosynthesis-USPTO_50k" \
    --input_max_length=100 \
    --num_beams=5 \
    --num_return_sequences=5 \
    --batch_size=16 \
    --output_dir="output"
```
You can do it in the same way for forward reaction prediction.

>"One remark, default value for retrosynthesis is not pointing to default v2 version but default="sagawa/ReactionT5-product-prediction"."
Thank you for letting me know. I fixed it.

**Comment by thegodone** [comment]
perfect thanks
